# Generated by Django 3.2.5 on 2021-07-06 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bids',
            new_name='Bid',
        ),
        migrations.RenameModel(
            old_name='comments',
            new_name='Comment',
        ),
    ]
