# Generated by Django 3.2.5 on 2021-07-06 12:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210706_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='auctions',
            field=models.ManyToManyField(related_name='watchlisted', to='auctions.Auction_List'),
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='user_info',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='user_info',
            field=models.ManyToManyField(related_name='my_watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
