# Generated by Django 3.2.5 on 2021-07-06 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210706_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='auctions',
            field=models.ManyToManyField(blank=True, related_name='watchlisted', to='auctions.Auction_List'),
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='user_info',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='user_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='my_watchlist', to='auctions.user'),
            preserve_default=False,
        ),
    ]
