# Generated by Django 3.2.5 on 2021-07-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210706_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_list',
            name='Pic_url',
            field=models.CharField(default='/', max_length=128),
            preserve_default=False,
        ),
    ]
