# Generated by Django 3.2.5 on 2021-07-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auction_list_pic_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_list',
            name='Active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction_list',
            name='Starting_bid',
            field=models.FloatField(default=1000),
            preserve_default=False,
        ),
    ]
