# Generated by Django 3.2.5 on 2021-07-06 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210706_1710'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chategory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='auction_list',
            old_name='Chategory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='Chategory_name',
            new_name='Category_name',
        ),
    ]
