# Generated by Django 3.2.5 on 2021-07-06 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210706_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='auc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='auc_comment', to='auctions.auction_list'),
            preserve_default=False,
        ),
    ]
